steps:
  - label: "Checkout Code"
    commands:
      - git clone https://github.com/tth3007/golang-demo.git
    # plugins:
    #   - git#v4.0.0:
    #       repository: "https://github.com/tth3007/golang-demo.git"
    #       branch: "main"

  
  - label: "Build Go Project"
    commands:
      - go mod tidy
      - go build -o myapp .
  
  - label: "Scan Code"
    commands:
      - go vet ./...
      - staticcheck ./...

  - label: "Run tests"
    commands:
      - go test ./tests
  
  # - label: "Run Tests and generate report"
  #   commands:
  #     - go install gotest.tools/gotestsum/cmd/gotestsum@latest && gotestsum --junitfile results.xml --format standard go test -v ./tests
  
  # - label: "Upload tests results"
  #   commands:
  #     - buildkite-agent artifact upload results.xml

  - label: "Build and Tag Docker Image"
    commands:
      - docker build -t myapp:latest .
  
  # - label: "Push Docker Image"
  #   commands:
  #     - docker tag myapp:latest <your-docker-repo>/myapp:latest
  #     - docker push <your-docker-repo>/myapp:latest